### ISSUE TITLE
trouble identifying no4sU as "TRUE" when loading the data

### ISSUE THREAD

**Issue by ivvukovic** [erhard-lab/grandR#24]
We were trying to load the data into the grandR and realized that our 0hr or no4sU condition is being read as "FALSE". It seems that there is a MAP column associated with my 0hr or no4sU condition and that is why the no4sU condition is read as "FALSE". I checked our grandSLAM run and didn't find anything wrong with it. I also don't understand why should there not be a MAP column associated with my no4sU condition - isn't it detecting background mismatches? There is always gonna be some background in all the samples. Does grand SLAM have a way of subtracting background if it can identify the "no4sU" condition? Our BAM files also look correct. 
Thank you!

**Comment by florianerhard** [comment]
Dear ivvukovic,
when you call Grand-slam, you need to tell it which sample are no4sU samples to properly estimate error rates (see [here](https://github.com/erhard-lab/gedi/wiki/GRAND-SLAM#regression-model-for-the-tc-rate-in-old-rna)). The easiest way is to include "no4sU" in the sample name. In that case, Grand-slam will not create a MAP column for that sample in the output file (simply because it doesn't make sense to do that). The presence or absence of a MAP column determines the "has.4sU" flag in the Coldata of the grandR object.
FE

**Comment by ivvukovic** [comment]
Thank you! Fixed it!
